### PR TITLE
Update to phpunit 9.5 and fix phpstan and phpcs issues

### PR DESCRIPTION
**Pull request by kimpepper**
- Moves test class to PSR-4 dir and updates composer.json
- Updates to PHPUnit 9.5
- Adds PHPStan and deprecation rules
- Fixes PHPStan errors:
  - Variable $raw in isset() always exists and is not nullable. 
  - PHP Deprecated:  Required parameter $term follows optional parameter $field
- Adds phpcs
- Fixes PSR12 coding standard issues

### CODE REVIEW

**Comment by pounard** [comment]
Thank you very much for this MR, but it seems that your code style goes too far in my opinion (it's a matter of taste, but I always keep `else if` instead of `elseif`, I find the two word variant much more readable).

Anyway, since you took time to do all of this, I'll merge it whether or not I like the style, because it's a lot of work and I appreciate it, and I won't fight against a minor taste issue !

Let me some time to fetch your branch branch, manually review it and run tests locally.

**Comment by pounard** [comment]
Everything seems OK, I ran tests locally and got one unrelated error due a stupid timezone conversion. Thanks a lot !

**Comment by pounard** [comment]
I pushed a 1.0.4 tag and release on packagist (sorry, I meant to do a 1.0.3 release but I got an error on packagist cause of the invalid SPDX licence identifier).

**Comment by kimpepper** [comment]
Thanks @pounard !

**Pull request merged**
